apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frifood-frontend-secrets
  namespace: fri-food-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azurekv
  target:
    name: frifood-frontend-secrets
    creationPolicy: Owner
  data:
    - secretKey: GOOGLE_MAPS_API_KEY
      remoteRef:
        key: google-maps-api-key
